name: yessfish
description: "YessFish - het sociale netwerk voor sportvissers"
publish_to: 'none'
version: 1.0.1+102

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  timeago: ^3.7.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  flutter_web_auth_2: ^4.1.0
  google_sign_in: ^6.2.1
  web_socket_channel: ^3.0.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
  firebase_analytics: ^12.4.3
  exif: ^3.3.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/yf_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/yf_icon_fg.png"
  min_sdk_android: 23
